version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: marko
      POSTGRES_PASSWORD: survivor
      POSTGRES_DB: survivor_fantasy
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
